name: rust-clipboard

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install sway for wayland
        run: sudo apt-get install -y sway xvbf xclip wl-clipboard
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Run x11 tests
        run: xvfb-run cargo test --verbose x11_clipboard
      - name: Run wayland tests
        run: |
          WLR_BACKENDS=headless WLR_LIBINPUT_NO_DEVICES=1 sway &
          WAYLAND_DISPLAY=/run/user/1000/wayland-1 cargo test --verbose wayland_clipboard
